### PR TITLE
Blur method

### PR DESCRIPTION
**Pull request by Mokto**
This PR exposes a 'blur' method to the search bar component.

### CODE REVIEW

**Comment by jhabdas** [comment]
+1

**Comment by jhabdas** [comment]
@Mokto looks like this PR goes part and parcel with #29?

**Comment by Mokto** [comment]
Both could be separated, but they look the same.

Should I be more clear ?

**Comment by jhabdas** [comment]
@Mokto Nah. Makes sense. Thanks for these updates. Saw they were in two separate commits in your repo. Backing off of your `master` now temporarily until blur is introduced here. Do you have any example usages of calling the blur method added when, for example, a separate `ListView` item is clicked?

**Comment by Mokto** [comment]
Actually, I'm using [redux](http://rackt.github.io/redux/) with react native. So I can trigger actions from your listview (for example) and receive it in Search Bar ;)

You can also use Flux.

Please let me know if you need anything else.

**Comment by jhabdas** [comment]
@Mokto any chance we could get this merged and a new NPM release? I've tried this out using the fork as discussed in #32 but would prefer to use the registry rather than Github. We need your help!

**Comment by Mokto** [comment]
I'm sorry but we have to wait @umhan35 response. I'm not the author of react-native-search-bar.

**Comment by umhan35** [comment]
Sorry for the delay. I'll merge it now and push another NPM release.

**Comment by umhan35** [comment]
2.3.0 is published. Thanks for contributing :smile:

**Comment by jhabdas** [comment]
Awesome! Thanks @umhan35. @Mokto sorry for tagging you inadvertently.

**Comment by nbastoWM** [comment]
How can I access a blur method of a search bar? 
I tryed with 
```
<SearchBar
          ref="searchBar"
          placeholder='Pesquisa'
          text={this.state.search}
          onChangeText={this.onChangeSearchText.bind(this)}
          onSearchButtonPress={this.onSearchPress.bind(this)}
          onCancelButtonPress={this.onCancelPress.bind(this)} />
```

and then ```this.refs.searchBar.blur();``` but with no success.
I want to "unfocus" the search bar when I go to another screen so the keyboard doesn't open when I get back to the search screen.

Thanks.

**Comment by eyaleizenberg** [comment]
So how do I blur the searchbar? I can't get it to work... :cry:

**Comment by Mokto** [comment]
Can you show your code please ?

I might be useful to help you.

**Comment by eyaleizenberg** [comment]
```coffeescript
<SearchBar ref='search' onSearchButtonPress={@initSearch} onCancelButtonPress={@cancelSearch} />
```

That's it pretty much. In my initSearch method I want to know what I need to do to blur the search bar.

**Comment by Mokto** [comment]
Sorry but I've never seen

onSearchButtonPress={@initSearch}

but this is what i would do :

```javascript
onPress() {
  this.refs.search.blur();
}
render() {
  return <SearchBar ref='search' onSearchButtonPress={this.onPress.bind(this)} />
}
```
onSearchButtonPress={buttonPress.bind(this)}

**Pull request merged**
