### PR TITLE
[android] Left margin

### PR DESCRIPTION
**Pull request by oxyii**
I'm not sure that this is correct way to fix left margin but it's works!

Related [SO](https://stackoverflow.com/questions/35695676/how-to-remove-space-on-the-left-side-of-android-searchview-which-is-not-part-of)

P.S. Thanks for the great component! I hope you continue to develop it! Especially in the part of Android-platform

### CODE REVIEW

**Comment by oxyii** [comment]
@iRoachie Wow! You are here too ))) Hi !!! About this PR:

**BEFORE**
WhatsApp Image 2019-10-20 at 00 46 09

**AFTER**
WhatsApp Image 2019-10-20 at 00 35 46

**Comment by iRoachie** [comment]
Haha Yea, I manage a few libs. Thanks for the contribution 🎉

**Comment by iRoachie** [comment]
Live in [v3.5.1](https://github.com/umhan35/react-native-search-bar/releases/tag/v3.5.1)

**Comment by oxyii** [comment]
@iRoachie Great! Thanks!

P.S. About RNN headers. I don't know why but on iOS platform search-bar with `searchBarStyle="minimal"` placed correct only with margin wrapper. I'm not sure that this is bug... Just for information

```jsx
<View style={{ marginTop: -8 }}>
  <SearchBar searchBarStyle="minimal" />
</View>
```

**Comment by iRoachie** [comment]
Seems to work fine for me

image


```jsx
<SafeAreaView style={styles.container}>
  <SearchBar searchBarStyle="minimal" />
</SafeAreaView>

...

const styles = StyleSheet.create({
  container: {
    backgroundColor: Colors.lighter,
    justifyContent: 'center',
  },
});
```

**Comment by oxyii** [comment]
@iRoachie I mean RNN iOS **native** header (in stack). But it can be issue of title position in RNN iOS header. I'm not sure.

```jsx
Navigation.registerComponent('searchbar', () => SearchBar);
Navigation.setRoot({
  root: {
    stack: {
      children: [
        {
          component: {
            name: 'screen.component',
            options: {
               topBar: {
                 title: {
                   component: {
                      name: 'searchbar',
                      alignment: 'fill',
                   },
                 },
               },
            },
          }
        }
      ],
    },
  }
});
```

**Comment by iRoachie** [comment]
Oh I don't know anything about react-native-navigation. I haven't used it in few years. I only use react-navigation

**Comment by oxyii** [comment]
@iRoachie Okay. If `<SearchBar searchBarStyle="minimal" />` did not have any vertical paddings on iOS then it's exactly RNN issue.

> Just for information

Thank you!

**Comment by oxyii** [comment]
@iRoachie About RNN iOS header - confirmed. This is a RNN [issue](https://github.com/wix/react-native-navigation/issues/5564)

**Pull request merged**
