### PR TITLE
remove react-native dependency

### PR DESCRIPTION
**Pull request by chirag04**

### CODE REVIEW

**Comment by chirag04** [comment]
fixes https://github.com/umhan35/react-native-search-bar/issues/53

**Comment by tomauty** [comment]
Guess I should've just done this :laughing:

**Comment by chirag04** [comment]
No problem. Can you merge this and bump the version?

**Comment by tomauty** [comment]
Oh, I'm not the maintainer. I also forked it and made the change, but never submitted a PR.

**Comment by chirag04** [comment]
ah! sorry my bad. cc @umhan35

**Pull request merged**
