### PR TITLE
Change README to "Install" and show "require".

### PR DESCRIPTION
**Pull request by joshuapinter**

### CODE REVIEW

**Comment by umhan35** [comment]
The update section is really updating. I'll update the require though.

**Comment by joshuapinter** [comment]
Fair enough. But you need to _install_ something before you _update_ it. ;)

**Comment by umhan35** [comment]
It's already in the readme file... https://github.com/umhan35/react-native-search-bar#installation

**Comment by joshuapinter** [comment]
Oh man. Sorry about that. Didn't see that for some reason. :eyes:

**Pull request closed without merging**
