### PR TITLE
Update for RN 0.25

### PR DESCRIPTION
**Pull request by alaycock**
Closes https://github.com/umhan35/react-native-search-bar/issues/73

### CODE REVIEW

**Comment by umhan35** [comment]
What's the backward compatibility? Will this PR make older versions RN not working?

**Comment by alaycock** [comment]
I tested on React Native 0.24.1 on one of my own applications, and it is backwards compatible. I don't know how far back it goes though.

In addition I updated the `.coffee` file, since I realized the .js is compiled from it, and so now they should match.

**Comment by umhan35** [comment]
My app locks at v0.21.0 as there is a bug in RN (157 comments so far but still not solved): https://github.com/facebook/react-native/issues/4968

I just tried your code on my app: it's also working on v0.21.

But anyways, I'll merge this PR and push another version onto NPM.

Thanks for your work!

**Comment by umhan35** [comment]
Just pushed 2.11.0 to npm 🎆

**Comment by alaycock** [comment]
I find that changing RN versions can sometimes trigger that error, and it requires the simulator, xcode, and the packager to restart. All looks good from my end on RN .25.1, no more warnings on 2.11.0.

**Pull request merged**
