### PR TITLE
Update index.d.ts to support style

### PR DESCRIPTION
**Pull request by Mokto**

### CODE REVIEW

**Comment by iRoachie** [comment]
Hey @Mokto there's no `style` prop for the SearchBar.

**Comment by Mokto** [comment]
But I am using the style prop, and it does modify the search-bar style.

Do you need an example ?

**Comment by iRoachie** [comment]
Could you show me your usage of this?

**Comment by Mokto** [comment]
https://github.com/monicahq/chandler/blob/develop/src/pages/Contacts/Navbar/Navbar.ios.tsx

Look at this page ;) The search bar is inserted into a react-native-navbar component.

**Comment by iRoachie** [comment]
You're right! Sorry about that mate, I was thinking purely on the values on the native side, but it seems React Native and UIManager do a little magic behind the scenes for some properties.

**Comment by iRoachie** [comment]
Published! https://github.com/umhan35/react-native-search-bar/releases/tag/v3.4.1

**Comment by Mokto** [comment]
Thanks !!

**Pull request merged**
