### PR TITLE
Focus method

### PR DESCRIPTION
**Pull request by Mokto**
Hi,

This PR exposes a 'focus' method to the search bar component.

CF #24 

Enjoy ;)

### CODE REVIEW

**Comment by alexisohayon** [comment]
This is exactly what I was looking for ;) Thanks a lot, when do you think it will be merged?
Or I can just clone your fork but you created different branches for blur / focus, and I need both :)

**Comment by Mokto** [comment]
If you want to clone my fork with both methods, use my master branch, focus and blur are on it :)

Hope it will be merged soon...

@umhan35 ??

**Comment by alexisohayon** [comment]
@Mokto Thanks, will do that :)

**Comment by umhan35** [comment]
merged in #42

**Pull request closed without merging**
