### PR TITLE
Fix button press event for RN 0.10.0

### PR DESCRIPTION
**Pull request by barakcoh**

### CODE REVIEW

**Comment by spencercarli** [comment]
Looks like line 70 also needs this fix https://github.com/umhan35/react-native-search-bar/pull/18/files#diff-396a729d0a957674e04a39dd6164ba05L70

**Comment by barakcoh** [comment]
yeah, guess you're right.. I didn't use the Cancel button :)

**Comment by spencercarli** [comment]
ha, so I opened up another PR (#19) to take care of both buttons

**Comment by barakcoh** [comment]
Closing as @spencercarli 's PR supersedes this one.

**Pull request closed without merging**
