### PR TITLE
Update for RN 0.40

### PR DESCRIPTION
**Pull request by Freddy03h**
Update headers according to the breaking change : https://github.com/facebook/react-native/releases/tag/v0.40.0

### CODE REVIEW

**Comment by wimgoeman** [comment]
I lost quite some time to discover I needed this change. Tested by installing from the fork and my issue is solved. Please integrate soon.

Solves #101 for me, since that seems to be the effect when the component (fails to/is not) compile(d).

**Comment by iRoachie** [comment]
Please merge 🙏🏽

**Comment by antonio0** [comment]
I tested these changes locally. At first, the component appears to work but when I tried to enable JS debug the app crashed. In the logs I see the following which I believe is related to the issue
`[tid:com.facebook.react.RCTBridgeQueue][RCTModuleData.mm:220] RCTBridge required dispatch_sync to load RCTAccessibilityManager. This may lead to deadlocks`.
Does anyone experience the same issue?

**Comment by iRoachie** [comment]
@antonio0 Could not replicate that issue friend.

**Comment by antonio0** [comment]
I did some more testing today. I don't have the issue anymore.
I think this PR is good and should be merged ASAP

**Comment by CarmeloXue** [comment]
@antonio0 still i meet this kind of problems like this 

image

so i wonder how you fix this problem? Thx

**Comment by antonio0** [comment]
@CarmeloXue Sorry, I wasn't able to replicate the issue anymore. I'm not sure what I've done for this to change

**Comment by nicinabox** [comment]
@umhan35 Can we get this merged?

**Comment by iRoachie** [comment]
@umhan35 Do you need someone to help maintain the project?

**Comment by crisys11** [comment]
same problem:

rn: 0.40
react-native-search-bar: 2.16.0

/Users/macbook/Documents/inmoblexapp/node_modules/react-native/React/Base/RCTBridge.h:65:1: Duplicate interface definition for class 'RCTBridge'

**Comment by umhan35** [comment]
Pushed to npm. Sorry for the delay.

**Comment by joshuapinter** [comment]
For those wondering, this was released in version `3.1.0` on npm.

**Pull request merged**
