### PR TITLE
More explicit Keyboard Mgmt Info

### PR DESCRIPTION
**Pull request by phoenixbox**
Hey there, I thought it would be helpful for other devs using this component to see in the README how to manage `showing/dismissing` the keyboard.

I missed it first time around, maybe this will help others.

Thanks for the lib :heart:

### CODE REVIEW

**Comment by michaelhelvey** [comment]
I agree!  I would note that with v2.13 the component now exposes on `unFocus` function as well, which maps to the `resignFirstResponder` method.  It might be good to point out the difference between `blur` and `unFocus`, so that folks coming from the native iOS world can see the difference without digging into source code.

Example: http://stackoverflow.com/questions/29882775/resignfirstresponder-vs-endediting-for-keyboard-dismissal

cc @umhan35

**Comment by umhan35** [comment]
@michaelhelvey Yeah, can you create a PR for this?

**Comment by umhan35** [comment]
2.14 is pushed to npm

**Comment by michaelhelvey** [comment]
@umhan35 Updated the docs in #81

**Pull request merged**
