### PR TITLE
Dimensions consistency when using textFieldBackgroundColor

### PR DESCRIPTION
**Pull request by hedblad**
- Changed height of search bar when using textFieldBackgroundColor to match the default one
- Added some padding to the left when using textFieldBackgroundColor

### CODE REVIEW

**Comment by umhan35** [comment]
@michaelhelvey Did you also find the change in this PR from `34 ` to `28` nessasary?

**Comment by michaelhelvey** [comment]
@umhan35 I didn't find the change necessary.  28 is slightly closer to the iOS default, I think, but I found that it caused some strange layout bugs when I was running tests.  I'd stick with 34, in my opinion.

**Comment by umhan35** [comment]
@michaelhelvey Thanks

**Comment by hedblad** [comment]
@michaelhelvey Sorry, this is a bit late, but what layout bugs did you find related to 28? Just curious, since I use 28 in production.

**Comment by michaelhelvey** [comment]
At one point, I thought that the smaller height was messing with the margin and padding of views lower down on the page (I didn't know why, but I suspected it was because the native `UISearchBar` frame was overflowing javascript styles, somehow).  A few weeks later, I found out that something else was doing that in my app.  I suppose I should have come back and updated this issue, but I forgot.  To the best of my knowledge now, 28 works fine. :)

**Comment by hedblad** [comment]
Got it, thanks! :)

**Pull request closed without merging**
