### PR TITLE
Added showCancelWhileEditing option

### PR DESCRIPTION
**Pull request by rmdort**
I have added a new option `showCancelWhileEditing` where by even if you force `showsCancelButton` to `false`, you can still make cancel button to appear when user is typing in the Search Text Field.

I have also made sure that `searchBarCancelButtonClicked` will show or hide cancel button taking the value from `_jsShowsCancelButton` and not force it to `NO`

### CODE REVIEW

**Comment by michaelhelvey** [comment]
Wouldn't it be easier to simply manage the cancel button's visibility with component state?  For example,

```js
<SearchBar
    showsCancelButton={this.state.showsCancelButton}
    onChangeText={() => {
        if (!this.state.showsCancelButton) this.setState({ showsCancelButton: true });
   }}
   // go on to hide the cancel button again when the user searches 
   // or cancels, or whatever you need.
/>
```
If you're worried about performance, you can just wrap `SearchBar` so that only the `SearchBar` is re-rendered on `setState`.

**Comment by rmdort** [comment]
Yes. We could do that, but we will lose the `Animation` when `Cancel` text shows and hides

**Comment by michaelhelvey** [comment]
Hm.  Good point.

**Comment by rmdort** [comment]
Yes, you are right. But we cant use the same prop `showsCancelButton`. Another way of doing this is by adding 2 Export methods in RNSearchBarManager.m and controlling the cancel button via componenDidUpdate in SearchBar.js, 

````
componentDidUpdate (prevProps) {
  if (prevProps.showCancelButton !== this.props.showCancelButton) {
    if (this.props.showCancelButton) {
      NativeModules.RNSearchBarManager.showCancelButton(ReactNative.findNodeHandle(this));
    } else {
      NativeModules.RNSearchBarManager.hideCancelButton(ReactNative.findNodeHandle(this));
    }
  }
},
````

The new prop name is `showCancelButton` . What do you think?

**Comment by michaelhelvey** [comment]
Why not just use the old prop name, and use the `componentWillReceiveProps` lifecycle hook? That way we can catch the prop change and animate it *before* the prop change gets passed along to the native property.

This way the result of the PR won't add to or change any of the user-facing API, *and* we'll get nice animations whenever we set the `showsCancelButton` prop in the javascript. 

i.e., add the two methods you suggest above to RNSearchBarManager, and then in SearchBar.js
```js
componentWillReceiveProps(nextProps) {
    if (nextProps.showsCancelButton !== this.props.showsCancelButton) {
      if (nextProps.showCancelButton) {
        NativeModules.RNSearchBarManager.showCancelButton(ReactNative.findNodeHandle(this));
      } else {
        NativeModules.RNSearchBarManager.hideCancelButton(ReactNative.findNodeHandle(this));
      }
    }
  },
```

I've just tested this approach on a device with a search bar built with the following props, and got perfect animations every time:

```js
<SearchBar
    ref={(bar) => { this.searchBar = bar; }}
    placeholder="Search"
    hideBackground={true}
    textFieldBackgroundColor={"#f1f1f1"}
    tintColor={AMColors.defaultGreen}
    showsCancelButton={this.state.showsCancelButton}
    onFocus={() => {
      this.setState({ showsCancelButton: true });
    }}
    onCancelButtonPress={() => {
      this.setState({ showsCancelButton: false });
      this.searchBar.unFocus();
    }}
    onSearchButtonPress={() => {
      this.setState({ showsCancelButton: false });
      this.searchBar.unFocus();
    }}
  />
```
What do you think, @umhan35 ?

**Comment by michaelhelvey** [comment]
(As a side note: I think this approach would perhaps allow us to actually remove this completely:

```objective-c
RCT_CUSTOM_VIEW_PROPERTY(showsCancelButton, BOOL, RNSearchBar) {
  BOOL value = [RCTConvert BOOL:json];
  view._jsShowsCancelButton = value;
  view.showsCancelButton = value;
}
```
since we're controlling the prop entirely via `RNSearchBarManager` methods.)

**Comment by rmdort** [comment]
Yes. The animation is sometimes choppy in simulator. But works well on device

Pushed the update. Let me know if you want me to change anything. 

1. Added new RCT_EXPORT_METHOD  `toggleCancelButton` 
2. Removed RCT_CUSTOM_VIEW_PROPERTY `showsCancelButton`
3. Removed `_jsShowsCancelButton`
4. Added `componentDidUpdate` to make `showsCancelButton` a controlled property

**Comment by michaelhelvey** [comment]
Two changes: 

1) Lifecycle methods like `componentDidUpdate` is not called on the initial render.  In your PR, if you statically set `showsCancelButton={true}`, it won't be applied. So we have to keep: 

```objective-c
RCT_CUSTOM_VIEW_PROPERTY(showsCancelButton, BOOL, RNSearchBar)
{
  BOOL value = [RCTConvert BOOL:json];
  view.showsCancelButton = value;
}
```
so that the initial rendering matches the javascript.

2) If we include this property, we have to catch and animate the prop change *before* the native view property gets it, or otherwise our nice animated methods won't be called until after the `showsCancelButton` is already set.

So we should use `componentWillReceiveProps` instead of `componentDidUpdate`:
```js
componentWillReceiveProps(nextProps) {
  if (nextProps.showsCancelButton !== this.props.showsCancelButton) {
    NativeModules.RNSearchBarManager.toggleCancelButton(ReactNative.findNodeHandle(this), this.props.showsCancelButton);
  }
},
```

**Comment by rmdort** [comment]
I was vary of calling a native module method in `componentWillReceiveProps`, thats why i used `componentDidUpdate`.  As far as i have tested, i don't see any UI issues. 

Thanks for the help @michaelhelvey

**Comment by FreshFlesh** [comment]
This is nice! Would love seeing this PR merged :)

**Comment by scarlac** [comment]
@michaelhelvey Any reason we can't merge this?

I basically re-created this PR without knowing, only to discover it was already in here (I should have checked first) so it'd be really nice to get it in the next release.

**Comment by michaelhelvey** [comment]
@scarlac I can't merge this.  I'm just a contributor helping out with preparing the PR.  Merging this is up to @umhan35.

**Comment by thomascharbit** [comment]
Let's hit the merge button! Yay! Please @umhan35 :)

**Comment by iRoachie** [comment]
@michaelhelvey Is this repo still active? I see they're issues from over 5 months ago. Is it safe to just fork this so someone can work on it actively? I'd like to add some of the functionality proposed in the issues.

**Comment by iRoachie** [comment]
Hey @rmdort new maintainer here. We recently released [v3.1.0](https://github.com/umhan35/react-native-search-bar/releases/tag/v3.1.0) so now your changes are out of sync with latest. Can you rebase your branch against the `next` branch?

**Comment by rmdort** [comment]
Rebase done. 👍

**Comment by iRoachie** [comment]
@rmdort Run me through this change one more time? Don't completely understand the use case

**Comment by iRoachie** [comment]
@rmdort I think I have a better way to handle this that's built upon your PR. You can check it out here https://github.com/umhan35/react-native-search-bar/pull/137

**Comment by iRoachie** [comment]
I still want you to get the credit, so I'll merge your PR then add on my part that handles the behavior on blur, cancel, search, and focus.

**Comment by iRoachie** [comment]
Released in [v3.3.0](https://github.com/umhan35/react-native-search-bar/releases/tag/v3.3.0). 💯

**Pull request merged**
